### PR TITLE
Add offsets for M2(14,3 14,4 14,5 14,6) [16.6, 16.6b1, 16.6.1]

### PR DESCRIPTION
**Pull request by braumye**
It passed the test on 14,3 with iPadOS 16.6.

### CODE REVIEW

**Comment by M2166** [comment]
同求 16·6m2无法安装

**Comment by PigsFlyOnTheRoad** [comment]
同求16·6m2无法安装

**Comment by braumye** [comment]
I've built an IPA to assist with the testing. Could you help me test it out? @PigsFlyOnTheRoad @M2166 

https://github.com/braumye/PureKFD/releases/tag/v1.0.0

**Comment by M2166** [comment]
可以的这就测试

**Comment by M2166** [comment]
测试刚才做了大家16·6M2安装成功感谢作者

**Comment by Lrdsnow** [comment]
Ty for your contribution

**Pull request merged**
